version: '3.6'
services:
  web:
    image: 'octobus/heptapod:latest'
    container_name: 'heptapod-server'
    restart: always
    hostname: 'devhouse.raynornet.xyz'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://devhouse.raynornet.xyz'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = ""
        gitlab_rails['smtp_user_name'] = ""
        gitlab_rails['smtp_password'] = ""
        gitlab_rails['smtp_domain'] = "raynornet.xyz"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['gitlab_email_from'] = 'heptapod@raynornet.xyz'
        gitlab_rails['gitlab_email_reply_to'] = 'heptapod@raynornet.xyz'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
      - '587:587'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
